# fly.toml app configuration file generated for yo-gpt-ai on 2023-05-20T06:09:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yo-gpt-ai"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
